# Welcome to Colab!

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
df = pd.read_csv('/content/xclan_fitness_usage_dataset.csv')

# Explore Data

In [12]:
df.head()

,user_id,session_date,session_duration_minutes,workout_module_used,calories_burned,completed_goal_checkin,signup_date,age,gender,goal,last_login_date,dropoff_flag
0,U0001,2025-05-13,30,Strength,153.41,No,2025-06-03,43,M,Build Muscle,2025-07-30,No
1,U0001,2025-05-15,66,Cardio,339.89,No,2025-06-03,43,M,Build Muscle,2025-07-30,No
2,U0001,2025-05-19,34,Cardio,214.16,Yes,2025-06-03,43,M,Build Muscle,2025-07-30,No
3,U0001,2025-05-22,88,Cardio,620.48,No,2025-06-03,43,M,Build Muscle,2025-07-30,No
4,U0001,2025-05-23,42,Cardio,322.88,Yes,2025-06-03,43,M,Build Muscle,2025-07-30,No

In [13]:
df.tail()

,user_id,session_date,session_duration_minutes,workout_module_used,calories_burned,completed_goal_checkin,signup_date,age,gender,goal,last_login_date,dropoff_flag
17420,U1000,2025-05-08,50,Yoga,286.81,Yes,2025-07-10,35,M,Stay Active,2025-07-05,Yes
17421,U1000,2025-05-16,37,HIIT,257.35,Yes,2025-07-10,35,M,Stay Active,2025-07-05,Yes
17422,U1000,2025-05-22,44,Cardio,405.46,Yes,2025-07-10,35,M,Stay Active,2025-07-05,Yes
17423,U1000,2025-06-11,33,Strength,181.38,No,2025-07-10,35,M,Stay Active,2025-07-05,Yes
17424,U1000,2025-07-05,67,HIIT,395.30,Yes,2025-07-10,35,M,Stay Active,2025-07-05,Yes

In [14]:
df.shape

(17425, 12)

In [15]:
df.columns

Index(['user_id', 'session_date', 'session_duration_minutes',
       'workout_module_used', 'calories_burned', 'completed_goal_checkin',
       'signup_date', 'age', 'gender', 'goal', 'last_login_date',
       'dropoff_flag'],
      dtype='object')

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17425 entries, 0 to 17424
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   user_id                   17425 non-null  object
 1   session_date              17425 non-null  object
 2   session_duration_minutes  17425 non-null  int64
 3   workout_module_used       17425 non-null  object
 4   calories_burned           17425 non-null  float64
 5   completed_goal_checkin    17425 non-null  object
 6   signup_date               17425 non-null  object
 7   age                       17425 non-null  int64
 8   gender                    17425 non-null  object
 9   goal                      17425 non-null  object
 10  last_login_date           17425 non-null  object
 11  dropoff_flag              17425 non-null  object
dtypes: float64(1), int64(2), object(9)
memory usage: 1.6+ MB

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df.isnull().sum()

user_id                     0
session_date                0
session_duration_minutes    0
workout_module_used         0
calories_burned             0
completed_goal_checkin      0
signup_date                 0
age                         0
gender                      0
goal                        0
last_login_date             0
dropoff_flag                0
dtype: int64

In [19]:
df.describe()

       session_duration_minutes  calories_burned           age
count              17425.000000     17425.000000  17425.000000
mean                  49.407518       370.534618     35.889928
std                   23.021020       189.593632     10.507614
min                   10.000000        50.210000     18.000000
25%                   29.000000       214.120000     27.000000
50%                   50.000000       355.550000     36.000000
75%                   69.000000       507.200000     45.000000
max                   89.000000       889.100000     54.000000

# Clean Data

In [20]:
# Shape before cleaning
print(df.shape)

(17425, 12)

In [21]:
# Shape after drop_duplicates
df = df.drop_duplicates()
print(df.shape)

(17425, 12)

In [22]:
# check nulls
print("\nNull values:\n", df.isnull().sum())

Null values:
 user_id                     0
session_date                0
session_duration_minutes    0
workout_module_used         0
calories_burned             0
completed_goal_checkin      0
signup_date                 0
age                         0
gender                      0
goal                        0
last_login_date             0
dropoff_flag                0
dtype: int64

In [23]:
# check types
print("\nDtypes:\n", df.dtypes)

Dtypes:
 user_id                      object
session_date                 object
session_duration_minutes      int64
workout_module_used          object
calories_burned             float64
completed_goal_checkin       object
signup_date                  object
age                           int64
gender                       object
goal                         object
last_login_date              object
dropoff_flag                 object
dtype: object

In [24]:
# Cast Dates
date_cols = ['session_date', 'signup_date', 'last_login_date']
df[date_cols] = df[date_cols].apply(pd.to_datetime)

In [25]:
# check neumeric range
print("\nage min:", df['age'].min(), "| max:", df['age'].max())
print("session_duration_minutes min:", df['session_duration_minutes'].min(), "| max:", df['session_duration_minutes'].max())
print("calories_burned min:", df['calories_burned'].min(), "| max:", df['calories_burned'].max())

age min: 18 | max: 54
session_duration_minutes min: 10 | max: 89
calories_burned min: 50.21 | max: 889.1

In [26]:
#check categoricals
cat_cols = ['gender', 'workout_module_used', 'completed_goal_checkin', 'dropoff_flag', 'goal']
for col in cat_cols:
    print(f"\n{col} unique values: {df[col].unique()}")

gender unique values: ['M' 'F']

workout_module_used unique values: ['Strength' 'Cardio' 'Yoga' 'Stretching' 'HIIT']

completed_goal_checkin unique values: ['No' 'Yes']

dropoff_flag unique values: ['No' 'Yes']

goal unique values: ['Build Muscle' 'Lose Weight' 'Stay Active']

In [27]:
df['completed_goal_checkin'] = df['completed_goal_checkin'].map({'Yes': 1, 'No': 0})
df['dropoff_flag'] = df['dropoff_flag'].map({'Yes': 1, 'No': 0})
df['gender'] = df['gender'].map({'M': 1, 'F': 0})

In [28]:
df = pd.get_dummies(df, columns=['workout_module_used', 'goal'])

In [29]:
bool_cols = df.select_dtypes(include='bool').columns
df[bool_cols] = df[bool_cols].astype(int)

In [30]:
df.columns = df.columns.str.replace(' ', '_')

In [31]:
# Final check
print("\nshape:", df.shape)
print("\ntypes:\n", df.dtypes)
print("\nhead:\n", df.head())

shape: (17425, 18)

types:
 user_id                                   object
session_date                      datetime64[ns]
session_duration_minutes                   int64
calories_burned                          float64
completed_goal_checkin                     int64
signup_date                       datetime64[ns]
age                                        int64
gender                                     int64
last_login_date                   datetime64[ns]
dropoff_flag                               int64
workout_module_used_Cardio                 int64
workout_module_used_HIIT                   int64
workout_module_used_Strength               int64
workout_module_used_Stretching             int64
workout_module_used_Yoga                   int64
goal_Build_Muscle                          int64
goal_Lose_Weight                           int64
goal_Stay_Active                           int64
dtype: object

head:
   user_id session_date  session_duration_minutes  calories_burned  \
0   U0001   2025-05-13                        30           153.41
1   U0001   2025-05-15                        66           339.89
2   U0001   2025-05-19                        34           214.16
3   U0001   2025-05-22                        88           620.48
4   U0001   2025-05-23                        42           322.88

   completed_goal_checkin signup_date  age  gender last_login_date  \
0                       0  2025-06-03   43       1      2025-07-30
1                       0  2025-06-03   43       1      2025-07-30
2                       1  2025-06-03   43       1      2025-07-30
3                       0  2025-06-03   43       1      2025-07-30
4                       1  2025-06-03   43       1      2025-07-30

   dropoff_flag  workout_module_used_Cardio  workout_module_used_HIIT  \
0             0                           0                         0
1             0                           1                         0
2             0                           1                         0
3             0                           1                         0
4             0                           1                         0

   workout_module_used_Strength  workout_module_used_Stretching  \
0                             1                               0
1                             0                               0
2                             0                               0
3                             0                               0
4                             0                               0

   workout_module_used_Yoga  goal_Build_Muscle  goal_Lose_Weight  \
0                         0                  1                 0
1                         0                  1                 0
2                         0                  1                 0
3                         0                  1                 0
4                         0                  1                 0

   goal_Stay_Active
0                 0
1                 0
2                 0
3                 0
4                 0